version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_CONNECTION_HOST=db
      - DB_CONNECTION_USER=postgres
      - DB_CONNECTION_PWD=your_db_password
      - DB_CONNECTION_DB=mgmapp
      - SECURITY_PASSWORD_PEPPER=your_pepper
      - SECURITY_JWT_SECRET=your_jwt_secret
    depends_on:
      - db
      - sonarqube
    networks:
      - my_custom_network
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: mgmapp
    ports:
      - "5432:5432"
    networks:
      - my_custom_network
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
    
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: