version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_CONNECTION_HOST=db
      - DB_CONNECTION_USER=postgres
      - DB_CONNECTION_PWD=your_db_password
      - DB_CONNECTION_DB=mgmapp
      - SECURITY_PASSWORD_PEPPER=your_pepper
      - SECURITY_JWT_SECRET=your_jwt_secret
    depends_on:
      - db
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: mgmapp
    ports:
      - "5432:5432"
