name: SDM x Roland CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        run: echo "${{ secrets.TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Docker Compose Build
        run: docker-compose -f docker-compose.yml build
        env:
          DB_CONNECTION_HOST: ${{ secrets.DB_CONNECTION_HOST }}
          DB_CONNECTION_USER: ${{ secrets.DB_CONNECTION_USER }}
          DB_CONNECTION_PWD: ${{ secrets.DB_CONNECTION_PWD }}
          DB_CONNECTION_DB: ${{ secrets.DB_CONNECTION_DB }}
          SECURITY_PASSWORD_PEPPER: ${{ secrets.SECURITY_PASSWORD_PEPPER }}
          SECURITY_JWT_SECRET: ${{ secrets.SECURITY_JWT_SECRET }}

      - name: Linting project
        run: npm run build & npm run lint

      - name: Docker Compose Push
        run: |
          docker-compose -f docker-compose.yml push
